import 'package:baqiyaat/features/learn/widgets/lesson1_card.dart';
import 'package:flutter/material.dart';

import '../../../models/lessons.dart';

class Alphabets extends StatelessWidget {
  const Alphabets({super.key});

  @override
  Widget build(BuildContext context) {
    final Map<String, Map<String, String>> alphabetForms = {
      "أ": {
        "id": "1",
        "initial": "أ",
        "middle": "ـأ",
        "final": "ـأ",
        "pronunciation": "اَﻟِﻒْ",
        "pronunciationTransliterationBn": "আলিফ",
        "pronunciationTransliterationEn": "Alif",
      },
      "ا": {
        "id": "1",
        "initial": "ا",
        "middle": "ـا",
        "final": "ـا",
        "pronunciation": "اَﻟِﻒْ",
        "pronunciationTransliterationBn": "আলিফ",
        "pronunciationTransliterationEn": "Alif",
      },
      "ب": {
        "id": "2",
        "initial": "بـ",
        "middle": "ـبـ",
        "final": "ﺐ",
        "pronunciation": "ﺑَﺎ",
        "pronunciationTransliterationBn": "বা",
        "pronunciationTransliterationEn": "Baa",
      },
      "ت": {
        "id": "3",
        "initial": "تـ",
        "middle": "ـتـ",
        "final": "ﺖ",
        "pronunciation": "ﺗَﺎ",
        "pronunciationTransliterationBn": "তা",
        "pronunciationTransliterationEn": "Taa",
      },
      "ث": {
        "id": "4",
        "initial": "ثـ",
        "middle": "ـثـ",
        "final": "ـث",
        "pronunciation": "ﺛَﺎ",
        "pronunciationTransliterationBn": "সা",
        "pronunciationTransliterationEn": "Saa",
      },
      "ج": {
        "id": "5",
        "initial": "جـ",
        "middle": "ـجـ",
        "final": "ـج",
        "pronunciation": "ﺟِﻴﻢ",
        "pronunciationTransliterationBn": "জীম",
        "pronunciationTransliterationEn": "Jeem",
      },
      "ح": {
        "id": "6",
        "initial": "حـ",
        "middle": "ـحـ",
        "final": "ـح",
        "pronunciation": "ﺣَﺎ",
        "pronunciationTransliterationBn": "‘হা",
        "pronunciationTransliterationEn": "‘Haa",
      },
      "خ": {
        "id": "7",
        "initial": "خـ",
        "middle": "ـخـ",
        "final": "ـخ",
        "pronunciation": "ﺧَﺎ",
        "pronunciationTransliterationBn": "খ",
        "pronunciationTransliterationEn": "Kho",
      },
      "د": {
        "id": "8",
        "initial": "د",
        "middle": "ـد",
        "final": "ـد",
        "pronunciation": "دَالْ",
        "pronunciationTransliterationBn": "দাল",
        "pronunciationTransliterationEn": "Daal",
      },
      "ذ": {
        "id": "9",
        "initial": "ذ",
        "middle": "ـذ",
        "final": "ـذ",
        "pronunciation": "ذَالْ",
        "pronunciationTransliterationBn": "যাল",
        "pronunciationTransliterationEn": "Zaal",
      },
      "ر": {
        "id": "10",
        "initial": "ر",
        "middle": "ـر",
        "final": "ـر",
        "pronunciation": "رَا",
        "pronunciationTransliterationBn": "র",
        "pronunciationTransliterationEn": "Rrow",
      },
      "ز": {
        "id": "11",
        "initial": "ز",
        "middle": "ـز",
        "final": "ـز",
        "pronunciation": "زَا",
        "pronunciationTransliterationBn": "জা",
        "pronunciationTransliterationEn": "Zaa",
      },
      "س": {
        "id": "12",
        "initial": "سـ",
        "middle": "ـسـ",
        "final": "ـس",
        "pronunciation": "ﺳِﻴْﻦْ",
        "pronunciationTransliterationBn": "সিন",
        "pronunciationTransliterationEn": "Seen",
      },
      "ش": {
        "id": "13",
        "initial": "شـ",
        "middle": "ـشـ",
        "final": "ـش",
        "pronunciation": "ﺷِﻴْﻦْ",
        "pronunciationTransliterationBn": "শিন",
        "pronunciationTransliterationEn": "Sheen",
      },
      "ص": {
        "id": "14",
        "initial": "صـ",
        "middle": "ـصـ",
        "final": "ـص",
        "pronunciation": "ﺻَﺎدْ",
        "pronunciationTransliterationBn": "সধ",
        "pronunciationTransliterationEn": "Sowdh",
      },
      "ض": {
        "id": "15",
        "initial": "ضـ",
        "middle": "ـضـ",
        "final": "ـض",
        "pronunciation": "ﺿَﺎدْ",
        "pronunciationTransliterationBn": "দধ",
        "pronunciationTransliterationEn": "Dowdh",
      },
      "ط": {
        "id": "16",
        "initial": "طـ",
        "middle": "ﻄ",
        "final": "ـط",
        "pronunciation": "ﻃَﺎ",
        "pronunciationTransliterationBn": "ত",
        "pronunciationTransliterationEn": "To‘w",
      },
      "ظ": {
        "id": "17",
        "initial": "ظـ",
        "middle": "ـظـ",
        "final": "ـظ",
        "pronunciation": "ﻇَﺎ",
        "pronunciationTransliterationBn": "জ‘ও",
        "pronunciationTransliterationEn": "Zo‘w",
      },
      "ع": {
        "id": "18",
        "initial": "عـ",
        "middle": "ـعـ",
        "final": "ـع",
        "pronunciation": "ﻋَﻴْﻦ",
        "pronunciationTransliterationBn": "‘আইন",
        "pronunciationTransliterationEn": "‘Aiyn",
      },
      "غ": {
        "id": "19",
        "initial": "غـ",
        "middle": "ـغـ",
        "final": "ـغ",
        "pronunciation": "ﻏَﻴْﻦ",
        "pronunciationTransliterationBn": "ঘইন",
        "pronunciationTransliterationEn": "Ghoiyn",
      },
      "ف": {
        "id": "20",
        "initial": "فـ",
        "middle": "ـفـ",
        "final": "ـف",
        "pronunciation": "ﻓَﺎ",
        "pronunciationTransliterationBn": "ফা",
        "pronunciationTransliterationEn": "Faa",
      },
      "ق": {
        "id": "21",
        "initial": "قـ",
        "middle": "ـقـ",
        "final": "ـق",
        "pronunciation": "قَﺎفْ",
        "pronunciationTransliterationBn": "ক্বওফ",
        "pronunciationTransliterationEn": "Qowf",
      },
      "ك": {
        "id": "22",
        "initial": "كـ",
        "middle": "ـكـ",
        "final": "ـك",
        "pronunciation": "ﻛَﺎفْ",
        "pronunciationTransliterationBn": "কাফ",
        "pronunciationTransliterationEn": "Kaaf",
      },
      "ل": {
        "id": "23",
        "initial": "لـ",
        "middle": "ـلـ",
        "final": "ـل",
        "pronunciation": "ﻻَمْ",
        "pronunciationTransliterationBn": "লাম",
        "pronunciationTransliterationEn": "Laam",
      },
      "م": {
        "id": "24",
        "initial": "مـ",
        "middle": "ـمـ",
        "final": "ـم",
        "pronunciation": "ﻣِﻴْﻢْ",
        "pronunciationTransliterationBn": "মীম",
        "pronunciationTransliterationEn": "Meem",
      },
      "ن": {
        "id": "25",
        "initial": "نـ",
        "middle": "ـنـ",
        "final": "ـن",
        "pronunciation": "ﻧُﻮْنْ",
        "pronunciationTransliterationBn": "নূন",
        "pronunciationTransliterationEn": "Noon",
      },
      "ه": {
        "id": "26",
        "initial": "هـ",
        "middle": "ـهـ",
        "final": "ـه",
        "pronunciation": "ﻫَﺎ",
        "pronunciationTransliterationBn": "হা",
        "pronunciationTransliterationEn": "Haa",
      },
      "و": {
        "id": "27",
        "initial": "و",
        "middle": "ـو",
        "final": "ـو",
        "pronunciation": "وَاوْ",
        "pronunciationTransliterationBn": "ওয়াও",
        "pronunciationTransliterationEn": "Waw",
      },
      "ء": {
        "id": "28",
        "initial": "ء",
        "middle": "ـء",
        "final": "ـء",
        "pronunciation": "همزة",
        "pronunciationTransliterationBn": "হামজা",
        "pronunciationTransliterationEn": "Hamza",
      },
      "ي": {
        "id": "29",
        "initial": "يـ",
        "middle": "ـيـ",
        "final": "ي",
        "pronunciation": "ﻳَﺎ",
        "pronunciationTransliterationBn": "ইয়া",
        "pronunciationTransliterationEn": "Yaa",
      },
    };

    return Scaffold(
      appBar: AppBar(
        title: const Text('Alphabets'),
        centerTitle: true,
      ),
      body: ListView.builder(
        itemCount: alphabetForms.entries.length,
        itemBuilder: (context, index) {
          final entry = alphabetForms.entries.elementAt(index);
          final String isolated = entry.key;
          final Map<String, String> forms = entry.value;

          // Create an Alphabet object for each entry
          final alphabet = Alphabet(
            id: forms['id']!,
            isolatedForm: isolated,
            initialForm: forms['initial']!,
            middleForm: forms['middle']!,
            endForm: forms['final']!,
            pronunciation: forms['pronunciation']!,
            pronunciationTransliterationBn:
                forms['pronunciationTransliterationBn']!,
            pronunciationTransliterationEn:
                forms['pronunciationTransliterationEn']!,
          );

          return Lesson1Card(alphabet: alphabet);
        },
      ),
    );
  }
}
